/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.codemodder.sample;

import io.codemodder.Runner;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // invoke the codemod runner
        Runner.run(
            List.of(ReadLinesCodemod.class),
            args
        );
    }
}
